# Generated by Django 3.1.1 on 2020-09-11 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200911_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('img_path', models.CharField(max_length=255, verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.categories', verbose_name='Направления деятельности')),
            ],
            options={
                'verbose_name': 'позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
    ]
