# Generated by Django 3.1.1 on 2020-09-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'позицию', 'verbose_name_plural': 'позиции'},
        ),
        migrations.AlterField(
            model_name='products',
            name='img_path',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
    ]
